### ISSUE TITLE
could please you describe your environment ? I go a lot of issue about torch version!

### ISSUE THREAD

**Issue by Lunabig** [Liyong8490/DnCNN-pytorch#2]
with torch 1.1.0 I got the error:
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument
Traceback (most recent call last):
  File "train_DnCNN.py", line 188, in <module>
    main()
  File "train_DnCNN.py", line 94, in main
    lossAarry[epoch - 1] = train(training_data_loader, optimizer, model, criterion, epoch)
  File "train_DnCNN.py", line 116, in train
    res = model(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/code/DnCNN-pytorch/models_DnCNN.py", line 131, in forward
    x = self.conv1(x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:383

with torch 0.4.0, I got the error:Traceback (most recent call last):
  File "train_DnCNN.py", line 188, in <module>
    main()
  File "train_DnCNN.py", line 94, in main
    lossAarry[epoch - 1] = train(training_data_loader, optimizer, model, criterion, epoch)
  File "train_DnCNN.py", line 116, in train
    res = model(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/code/DnCNN-pytorch/models_DnCNN.py", line 131, in forward
    x = self.conv1(x)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDNN_STATUS_MAPPING_ERRORpython.
could you please give me some hints to solve the errors?

**Comment by Lunabig** [comment]
I try to used torch 1.1.0 with cuda 10, it worked. thanks in advanced!
